# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'myVK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myVK

pod 'Alamofire', '~> 5.0.0-beta.5'
pod 'Kingfisher'
pod 'RealmSwift'
end
